# Generated by Django 4.2.19 on 2025-03-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lineitem',
            table='order_line_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
