# Generated by Django 4.2.19 on 2025-03-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_lineitem_table_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
