# Generated by Django 4.2.19 on 2025-03-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcart',
            table='shopping_cart',
        ),
        migrations.AlterModelTable(
            name='shoppingcartitem',
            table='shopping_cart_item',
        ),
    ]
