# Generated by Django 4.2.19 on 2025-02-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('is_public', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
